### ISSUE TITLE
Server Spawning Trouble 

### ISSUE THREAD

**Issue by higuita** [ArtixAllMighty/PetBuddy2016#11]
Hi

I tried to enable this on a server and was unable to spawn the pet...
So please add support for server or post some help how to enable this on the server, if it should have worked already

**Comment by AbsolemJackdaw** [comment]
mod needs to be installed on server and client.

if this was the case, and it didn't work, i'll look into it.

**Comment by whatthedrunk** [comment]
Yeah I just wanted to test it with all the mods 2 but I have no buddy lol

**Comment by P3rf3ctXZer0** [comment]
@whatthedrunk if you are familiar with multimc my friends and I sometimes play together.

**Comment by AbsolemJackdaw** [comment]
can i see some logs higuita ? I can spawn buddies on my server just fine

**Comment by KamiSami** [comment]
I cannot spawn pet buddy in server either

**Comment by AbsolemJackdaw** [comment]
what do you do ? what is installed ? can i have a log of the server and the client please ?? mine is spawning just fine. you need to press 'p' to spawn it (p for pet) if any other mod uses this key, change it in the keybinds.
Again, without logs, it's like looking for a needle in a bale of hay ... so please, I need a log to help you guys out !

**Comment by neoalpha** [comment]
When I press the p key on my client machine, the buddy does not appear and the following error is logged:

```
[14:32:43] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: net/minecraft/client/resources/DefaultPlayerSkin
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_121]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:679) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384) [lh.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/resources/DefaultPlayerSkin
	at subaraki.petbuddy.entity.EntityPetBuddy.<init>(EntityPetBuddy.java:63) ~[EntityPetBuddy.class:?]
	at subaraki.petbuddy.hooks.StowOrSummonLogic.givePet(StowOrSummonLogic.java:26) ~[StowOrSummonLogic.class:?]
	at subaraki.petbuddy.network.PacketStowOrSummonPet$PacketStowOrSummonPetHandler.lambda$onMessage$0(PacketStowOrSummonPet.java:52) ~[PacketStowOrSummonPet$PacketStowOrSummonPetHandler.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.resources.DefaultPlayerSkin
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	at subaraki.petbuddy.entity.EntityPetBuddy.<init>(EntityPetBuddy.java:63) ~[EntityPetBuddy.class:?]
	at subaraki.petbuddy.hooks.StowOrSummonLogic.givePet(StowOrSummonLogic.java:26) ~[StowOrSummonLogic.class:?]
	at subaraki.petbuddy.network.PacketStowOrSummonPet$PacketStowOrSummonPetHandler.lambda$onMessage$0(PacketStowOrSummonPet.java:52) ~[PacketStowOrSummonPet$PacketStowOrSummonPetHandler.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	at subaraki.petbuddy.entity.EntityPetBuddy.<init>(EntityPetBuddy.java:63) ~[EntityPetBuddy.class:?]
	at subaraki.petbuddy.hooks.StowOrSummonLogic.givePet(StowOrSummonLogic.java:26) ~[StowOrSummonLogic.class:?]
	at subaraki.petbuddy.network.PacketStowOrSummonPet$PacketStowOrSummonPetHandler.lambda$onMessage$0(PacketStowOrSummonPet.java:52) ~[PacketStowOrSummonPet$PacketStowOrSummonPetHandler.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more
[14:33:49] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: net/minecraft/client/resources/DefaultPlayerSkin
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_121]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:679) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384) [lh.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/resources/DefaultPlayerSkin
	at subaraki.petbuddy.entity.EntityPetBuddy.<init>(EntityPetBuddy.java:63) ~[EntityPetBuddy.class:?]
	at subaraki.petbuddy.hooks.StowOrSummonLogic.givePet(StowOrSummonLogic.java:26) ~[StowOrSummonLogic.class:?]
	at subaraki.petbuddy.network.PacketStowOrSummonPet$PacketStowOrSummonPetHandler.lambda$onMessage$0(PacketStowOrSummonPet.java:52) ~[PacketStowOrSummonPet$PacketStowOrSummonPetHandler.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more
[14:33:58] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: net/minecraft/client/resources/DefaultPlayerSkin
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_121]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:679) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384) [lh.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/resources/DefaultPlayerSkin
	at subaraki.petbuddy.entity.EntityPetBuddy.<init>(EntityPetBuddy.java:63) ~[EntityPetBuddy.class:?]
	at subaraki.petbuddy.hooks.StowOrSummonLogic.givePet(StowOrSummonLogic.java:26) ~[StowOrSummonLogic.class:?]
	at subaraki.petbuddy.network.PacketStowOrSummonPet$PacketStowOrSummonPetHandler.lambda$onMessage$0(PacketStowOrSummonPet.java:52) ~[PacketStowOrSummonPet$PacketStowOrSummonPetHandler.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more
[14:34:01] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: net/minecraft/client/resources/DefaultPlayerSkin
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_121]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:679) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384) [lh.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/resources/DefaultPlayerSkin
	at subaraki.petbuddy.entity.EntityPetBuddy.<init>(EntityPetBuddy.java:63) ~[EntityPetBuddy.class:?]
	at subaraki.petbuddy.hooks.StowOrSummonLogic.givePet(StowOrSummonLogic.java:26) ~[StowOrSummonLogic.class:?]
	at subaraki.petbuddy.network.PacketStowOrSummonPet$PacketStowOrSummonPetHandler.lambda$onMessage$0(PacketStowOrSummonPet.java:52) ~[PacketStowOrSummonPet$PacketStowOrSummonPetHandler.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more

```

Since it is a server, the client's classes are not installed.
"net/minecraft/client/resources/DefaultPlayerSkin" does not exist.
What should I do?

**Comment by AbsolemJackdaw** [comment]
wait and let me upload a fix x) This is the first report I had for this error. thank you very much !
