### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by Davastating** [ArtixAllMighty/PetBuddy2016#24]
I'm getting following error message when i put an item in the appearance changing slot:

> [23:26:35] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: net/minecraft/client/model/ModelBiped
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_101]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_101]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/model/ModelBiped
	at subaraki.petbuddy.gui.server.ContainerPetChest.func_184996_a(ContainerPetChest.java:85) ~[ContainerPetChest.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:1158) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:38) ~[lf.class:?]
	at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:12) ~[lf.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_101]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_101]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.model.ModelBiped
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_101]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_101]
	at subaraki.petbuddy.gui.server.ContainerPetChest.func_184996_a(ContainerPetChest.java:85) ~[ContainerPetChest.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:1158) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:38) ~[lf.class:?]
	at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:12) ~[lf.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_101]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_101]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_101]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_101]
	at subaraki.petbuddy.gui.server.ContainerPetChest.func_184996_a(ContainerPetChest.java:85) ~[ContainerPetChest.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:1158) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:38) ~[lf.class:?]
	at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:12) ~[lf.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_101]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_101]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more

Also.. is it normal that the buddy randomly teleports some blocks away when i right-click him to access his inventory?

**Comment by AbsolemJackdaw** [comment]
what ? ._. the game can't find the base of all biped models
oh wait, indeed. modelbiped should only be accesed client side. 

but the model isnt accesedd in the container... ? 
i'll look into it

**Comment by Davastating** [comment]
It changes the appearance (client side) but spams the server with these errors.

**Comment by AbsolemJackdaw** [comment]
btw yes, it's normal. when accessing it's inventory, the buddy can still move around.
