### ISSUE TITLE
Ticking entity

### ISSUE THREAD

**Issue by SenZ01** [ArtixAllMighty/PetBuddy2016#29]
java.lang.NullPointerException: Ticking entity
	at subaraki.petbuddy.entity.EntityPetBuddy.func_70097_a(EntityPetBuddy.java:196)
	at com.Fishmod.mod_LavaCow.entities.tameable.EntityScarecrow.func_70636_d(EntityScarecrow.java:151)
	at net.minecraft.entity.EntityLivingBase.TickCentral_TrueOnUpdateTick(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.TickCentral_TrueOnUpdateTick(EntityLiving.java:295)
	at com.Fishmod.mod_LavaCow.entities.tameable.EntityFishTameable.TickCentral_TrueOnUpdateTick(EntityFishTameable.java:219)
	at com.Fishmod.mod_LavaCow.entities.tameable.EntityScarecrow.TickCentral_TrueOnUpdateTick(EntityScarecrow.java:119)
	at com.github.terminatornl.tickcentral.api.TickHub.trueOnUpdate(TickHub.java:56)
	at com.github.terminatornl.tickcentral.api.TickInterceptor.redirectOnUpdate(TickInterceptor.java:28)
	at com.Fishmod.mod_LavaCow.entities.tameable.EntityScarecrow.func_70071_h_(EntityScarecrow.java)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at subaraki.petbuddy.entity.EntityPetBuddy.func_70097_a(EntityPetBuddy.java:196)
	at com.Fishmod.mod_LavaCow.entities.tameable.EntityScarecrow.func_70636_d(EntityScarecrow.java:151)
	at net.minecraft.entity.EntityLivingBase.TickCentral_TrueOnUpdateTick(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.TickCentral_TrueOnUpdateTick(EntityLiving.java:295)
	at com.Fishmod.mod_LavaCow.entities.tameable.EntityFishTameable.TickCentral_TrueOnUpdateTick(EntityFishTameable.java:219)
	at com.Fishmod.mod_LavaCow.entities.tameable.EntityScarecrow.TickCentral_TrueOnUpdateTick(EntityScarecrow.java:119)
	at com.github.terminatornl.tickcentral.api.TickHub.trueOnUpdate(TickHub.java:56)
	at com.github.terminatornl.tickcentral.api.TickInterceptor.redirectOnUpdate(TickInterceptor.java:28)
	at com.Fishmod.mod_LavaCow.entities.tameable.EntityScarecrow.func_70071_h_(EntityScarecrow.java)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)

-- Entity being ticked --
Details:
	Entity Type: mod_lavacow:scarecrow (com.Fishmod.mod_LavaCow.entities.tameable.EntityScarecrow)
	Entity ID: 10148
	Entity Name: Scarecrow
	Entity's Exact location: 308.91, 72.00, 783.25
	Entity's Block location: World: (308,72,783), Chunk: (at 4,4,15 in 19,48; contains blocks 304,0,768 to 319,255,783), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,0,512 to 511,255,1023)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: BBOP7
	All players: 1 total; [EntityPlayerMP['SSenZ0'/497, l='BBOP7', x=307.71, y=72.00, z=786.62]]
	Chunk stats: ServerChunkCache: 578 Drop: 0
	Level seed: 4519059594077345360
	Level generator: ID 07 - OTG, ver 0. Features enabled: true
	Level generator options: OpenTerrainGenerator
	Level spawn location: World: (-360,66,1016), Chunk: (at 8,4,8 in -23,63; contains blocks -368,0,1008 to -353,255,1023), Region: (-1,1; contains chunks -32,32 to -1,63, blocks -512,0,512 to -1,255,1023)
	Level time: 41136 game time, 41136 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 57640 (now: false), thunder time: 29907 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

**Comment by AbsolemJackdaw** [comment]
discarting issue due to date and stale / old version
